//! scans current dir for package.json / docker-compose.yml / Procfile and
//! suggests a draft pulse.toml.

use std::path::Path;

use serde::Deserialize;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Suggestion {
    pub name: String,
    pub cmd: String,
    pub source: &'static str,
}

/// run every parser against the dir, dedupe by name (first wins).
pub fn scan(dir: &Path) -> Vec<Suggestion> {
    let mut out: Vec<Suggestion> = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for s in from_package_json(dir)
        .into_iter()
        .chain(from_compose(dir))
        .chain(from_procfile(dir))
    {
        if seen.insert(s.name.clone()) {
            out.push(s);
        }
    }
    out
}

#[derive(Debug, Deserialize)]
struct PackageJson {
    #[serde(default)]
    scripts: std::collections::BTreeMap<String, String>,
}

pub fn from_package_json(dir: &Path) -> Vec<Suggestion> {
    let p = dir.join("package.json");
    let raw = match std::fs::read_to_string(&p) {
        Ok(r) => r,
        Err(_) => return Vec::new(),
    };
    parse_package_json(&raw)
}

pub fn parse_package_json(raw: &str) -> Vec<Suggestion> {
    let pkg: PackageJson = match serde_json::from_str(raw) {
        Ok(p) => p,
        Err(_) => return Vec::new(),
    };
    let interesting = ["dev", "start", "watch", "test:watch", "serve"];
    pkg.scripts
        .into_iter()
        .filter(|(k, _)| interesting.contains(&k.as_str()))
        .map(|(k, _)| Suggestion {
            name: k.clone(),
            cmd: format!("npm run {k}"),
            source: "package.json",
        })
        .collect()
}

#[derive(Debug, Deserialize)]
struct Compose {
    #[serde(default)]
    services: std::collections::BTreeMap<String, serde_yaml::Value>,
}

pub fn from_compose(dir: &Path) -> Vec<Suggestion> {
    for name in ["docker-compose.yml", "docker-compose.yaml", "compose.yml"] {
        let p = dir.join(name);
        if let Ok(raw) = std::fs::read_to_string(&p) {
            return parse_compose(&raw);
        }
    }
    Vec::new()
}

pub fn parse_compose(raw: &str) -> Vec<Suggestion> {
    let c: Compose = match serde_yaml::from_str(raw) {
        Ok(c) => c,
        Err(_) => return Vec::new(),
    };
    c.services
        .into_keys()
        .map(|n| Suggestion {
            name: n.clone(),
            cmd: format!("docker compose up {n}"),
            source: "docker-compose",
        })
        .collect()
}

pub fn from_procfile(dir: &Path) -> Vec<Suggestion> {
    let p = dir.join("Procfile");
    let raw = match std::fs::read_to_string(&p) {
        Ok(r) => r,
        Err(_) => return Vec::new(),
    };
    parse_procfile(&raw)
}

pub fn parse_procfile(raw: &str) -> Vec<Suggestion> {
    let mut out = Vec::new();
    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((name, cmd)) = line.split_once(':') {
            let name = name.trim();
            let cmd = cmd.trim();
            if name.is_empty() || cmd.is_empty() {
                continue;
            }
            out.push(Suggestion {
                name: name.to_string(),
                cmd: cmd.to_string(),
                source: "Procfile",
            });
        }
    }
    out
}

/// render a draft pulse.toml. keeps it commented so the user knows what's what.
pub fn render_draft(suggestions: &[Suggestion]) -> String {
    let mut s = String::new();
    s.push_str("# draft pulse.toml — generated by `pulse init`.\n");
    s.push_str("# review these, tweak the cmds, then remove this comment.\n\n");
    if suggestions.is_empty() {
        s.push_str("# nothing found. add a service manually:\n");
        s.push_str("# [[service]]\n# name = \"api\"\n# cmd = \"cargo run\"\n");
        return s;
    }
    let colors = ["cyan", "magenta", "yellow", "green", "blue", "red"];
    for (i, sug) in suggestions.iter().enumerate() {
        s.push_str(&format!("# from {}\n", sug.source));
        s.push_str("[[service]]\n");
        s.push_str(&format!("name = {:?}\n", sug.name));
        s.push_str(&format!("cmd = {:?}\n", sug.cmd));
        s.push_str(&format!("color = {:?}\n\n", colors[i % colors.len()]));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn package_json_picks_dev_and_start() {
        let raw = r#"{
  "name": "x",
  "scripts": {
    "dev": "next dev",
    "start": "next start",
    "lint": "eslint .",
    "test:watch": "jest --watch"
  }
}"#;
        let s = parse_package_json(raw);
        let names: Vec<_> = s.iter().map(|x| x.name.as_str()).collect();
        assert!(names.contains(&"dev"));
        assert!(names.contains(&"start"));
        assert!(names.contains(&"test:watch"));
        assert!(!names.contains(&"lint"));
    }

    #[test]
    fn compose_reads_services() {
        let raw = r#"
services:
  api:
    image: myapi
  db:
    image: postgres
"#;
        let s = parse_compose(raw);
        let names: Vec<_> = s.iter().map(|x| x.name.as_str()).collect();
        assert!(names.contains(&"api"));
        assert!(names.contains(&"db"));
    }

    #[test]
    fn procfile_parses_basic() {
        let raw = "web: rails s\nworker: bundle exec sidekiq\n# comment\n";
        let s = parse_procfile(raw);
        assert_eq!(s.len(), 2);
        assert_eq!(s[0].name, "web");
        assert_eq!(s[0].cmd, "rails s");
    }

    #[test]
    fn draft_is_valid_toml() {
        let s = vec![Suggestion {
            name: "api".into(),
            cmd: "npm run dev".into(),
            source: "package.json",
        }];
        let rendered = render_draft(&s);
        // must be parseable by our own config
        assert!(crate::config::parse(&rendered).is_ok());
    }

    #[test]
    fn draft_with_no_suggestions() {
        let out = render_draft(&[]);
        assert!(out.contains("nothing found"));
    }
}
